// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function CheckUVInstalled() {
  return window['go']['main']['App']['CheckUVInstalled']();
}

export function CreateConfig(arg1) {
  return window['go']['main']['App']['CreateConfig'](arg1);
}

export function DetectPythonProject(arg1) {
  return window['go']['main']['App']['DetectPythonProject'](arg1);
}

export function DownloadAndInstall(arg1) {
  return window['go']['main']['App']['DownloadAndInstall'](arg1);
}

export function GetAppDetail(arg1) {
  return window['go']['main']['App']['GetAppDetail'](arg1);
}

export function GetInstalledApps() {
  return window['go']['main']['App']['GetInstalledApps']();
}

export function GetReadme(arg1) {
  return window['go']['main']['App']['GetReadme'](arg1);
}

export function GetRepoInfo(arg1) {
  return window['go']['main']['App']['GetRepoInfo'](arg1);
}

export function GetUVVersion() {
  return window['go']['main']['App']['GetUVVersion']();
}

export function GetUpdateCount() {
  return window['go']['main']['App']['GetUpdateCount']();
}

export function InstallUV() {
  return window['go']['main']['App']['InstallUV']();
}

export function LaunchApp(arg1) {
  return window['go']['main']['App']['LaunchApp'](arg1);
}

export function OpenExternal(arg1) {
  return window['go']['main']['App']['OpenExternal'](arg1);
}

export function UninstallApp(arg1) {
  return window['go']['main']['App']['UninstallApp'](arg1);
}

export function UpdateLaunchType(arg1, arg2) {
  return window['go']['main']['App']['UpdateLaunchType'](arg1, arg2);
}
