// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckForUpdates():Promise<Array<Record<string, string>>>;

export function CheckUVInstalled():Promise<boolean>;

export function CreateConfig(arg1:string):Promise<void>;

export function DetectPythonProject(arg1:string):Promise<main.ProjectInfo>;

export function DownloadAndInstall(arg1:string):Promise<string>;

export function GetAppDetail(arg1:string):Promise<Record<string, any>>;

export function GetInstalledApps():Promise<Array<main.IndexEntry>>;

export function GetReadme(arg1:string):Promise<string>;

export function GetRepoInfo(arg1:string):Promise<main.RepoInfo>;

export function GetUVVersion():Promise<string>;

export function GetUpdateCount():Promise<number>;

export function InstallUV():Promise<string>;

export function LaunchApp(arg1:string):Promise<void>;

export function OpenExternal(arg1:string):Promise<void>;

export function UninstallApp(arg1:string):Promise<void>;

export function UpdateLaunchType(arg1:string,arg2:string):Promise<void>;
